[tool.pytest.ini_options]
filterwarnings = [
    "error::DeprecationWarning",
    "ignore::DeprecationWarning:pytest.*:",
]


[tool.mypy]
ignore_missing_imports = true
check_untyped_defs = true
no_strict_optional = true

# https://github.com/python/mypy/issues/10632
[[tool.mypy.overrides]]
module = ["requests", "pytz"]
ignore_missing_imports = true

[tool.ruff]
exclude = [".venv", "venv", "__pycache__"]
line-length = 80
# TODO: Add when available: "E266", "E203"
lint.ignore = ["E501", "E741", "E402"]
lint.select = ['E', 'F', 'W', 'I']